# Generated by Django 5.0.1 on 2024-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSetting',
        ),
    ]
