# Generated by Django 5.0.1 on 2024-04-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_imagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting.', max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('file', models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Image')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated_date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created_date')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('name',),
            },
        ),
    ]
